import Foundation
import SQLite3

extension CoreTests {
    static func analyticsChecks(folder: URL) throws {
        let resolver = ProjectResolver()
        let repository = folder.appendingPathComponent("repo with spaces"), nested = repository.appendingPathComponent("Sources")
        try FileManager.default.createDirectory(at: nested, withIntermediateDirectories: true)
        func git(_ args: [String]) throws {
            let process = Process(); process.executableURL = URL(fileURLWithPath: "/usr/bin/git")
            process.arguments = ["-C", repository.path] + args
            process.standardOutput = FileHandle.nullDevice; process.standardError = FileHandle.nullDevice
            try process.run(); process.waitUntilExit()
            expect(process.terminationStatus == 0, "test Git fixture command succeeds")
        }
        try git(["init", "--initial-branch=main"])
        try git(["-c", "user.name=Fixture", "-c", "user.email=fixture@example.invalid", "-c", "commit.gpgsign=false", "commit", "--allow-empty", "-m", "Fixture"])
        let worktree = folder.appendingPathComponent("linked worktree")
        try git(["worktree", "add", "-b", "fixture", worktree.path])
        expect(resolver.resolve(repository.path) == resolver.resolve(nested.path), "repository subdirectory shares project identity")
        expect(resolver.resolve(repository.path) == resolver.resolve(worktree.path), "linked worktree shares the main repository identity")
        let alias = folder.appendingPathComponent("repo alias")
        try FileManager.default.createSymbolicLink(at: alias, withDestinationURL: repository)
        expect(resolver.resolve(alias.path) == resolver.resolve(repository.path), "symlinked workspaces do not create duplicate projects")
        // Entirely file-created fixtures: production discovery needs no Git executable.
        let minimal = folder.appendingPathComponent("metadata-only/main")
        let minimalGit = minimal.appendingPathComponent(".git")
        try FileManager.default.createDirectory(at: minimalGit.appendingPathComponent("objects"), withIntermediateDirectories: true)
        try FileManager.default.createDirectory(at: minimalGit.appendingPathComponent("refs"), withIntermediateDirectories: true)
        try "ref: refs/heads/main\n".write(to: minimalGit.appendingPathComponent("HEAD"), atomically: true, encoding: .utf8)
        expect(resolver.resolve(minimal.path).id == "git:" + minimalGit.path, "file-only repository discovery works without developer tools")
        let linked = folder.appendingPathComponent("metadata-only/linked")
        let linkedGit = minimalGit.appendingPathComponent("worktrees/linked")
        try FileManager.default.createDirectory(at: linkedGit, withIntermediateDirectories: true)
        try FileManager.default.createDirectory(at: linked.appendingPathComponent("Sources"), withIntermediateDirectories: true)
        try "gitdir: ../main/.git/worktrees/linked\n".write(to: linked.appendingPathComponent(".git"), atomically: true, encoding: .utf8)
        try "ref: refs/heads/linked\n".write(to: linkedGit.appendingPathComponent("HEAD"), atomically: true, encoding: .utf8)
        try "../..\n".write(to: linkedGit.appendingPathComponent("commondir"), atomically: true, encoding: .utf8)
        expect(resolver.resolve(linked.path) == resolver.resolve(minimal.path), "relative gitdir and commondir merge file-only linked worktrees")
        expect(resolver.resolve(linked.appendingPathComponent("Sources").path) == resolver.resolve(minimal.path), "file-only linked worktree subdirectories merge with the repository")
        let absoluteLink = folder.appendingPathComponent("metadata-only/absolute")
        try FileManager.default.createDirectory(at: absoluteLink, withIntermediateDirectories: true)
        try "gitdir: \(linkedGit.path)\n".write(to: absoluteLink.appendingPathComponent(".git"), atomically: true, encoding: .utf8)
        expect(resolver.resolve(absoluteLink.path) == resolver.resolve(minimal.path), "absolute gitdir pointers merge with the same repository")
        let broken = folder.appendingPathComponent("metadata-only/broken")
        try FileManager.default.createDirectory(at: broken, withIntermediateDirectories: true)
        try "gitdir: missing\n".write(to: broken.appendingPathComponent(".git"), atomically: true, encoding: .utf8)
        expect(resolver.resolve(broken.path).id == "directory:" + broken.path, "missing repository metadata retains an ordinary directory project")
        let malformed = folder.appendingPathComponent("metadata-only/malformed")
        try FileManager.default.createDirectory(at: malformed, withIntermediateDirectories: true)
        try "gitdir: \(minimalGit.path)\nextra line\n".write(to: malformed.appendingPathComponent(".git"), atomically: true, encoding: .utf8)
        expect(resolver.resolve(malformed.path).id == "directory:" + malformed.path, "malformed multi-line Git pointers do not redirect discovery")
        let oversized = folder.appendingPathComponent("metadata-only/oversized")
        try FileManager.default.createDirectory(at: oversized, withIntermediateDirectories: true)
        try ("gitdir: " + String(repeating: "a", count: 16_385)).write(to: oversized.appendingPathComponent(".git"), atomically: true, encoding: .utf8)
        expect(resolver.resolve(oversized.path).id == "directory:" + oversized.path, "oversized Git pointer reads are bounded and fall back safely")
        let brokenCommon = folder.appendingPathComponent("metadata-only/broken-common/.git")
        try FileManager.default.createDirectory(at: brokenCommon.appendingPathComponent("objects"), withIntermediateDirectories: true)
        try "ref: refs/heads/main\n".write(to: brokenCommon.appendingPathComponent("HEAD"), atomically: true, encoding: .utf8)
        try "\n".write(to: brokenCommon.appendingPathComponent("commondir"), atomically: true, encoding: .utf8)
        expect(resolver.resolve(brokenCommon.deletingLastPathComponent().path).id.hasPrefix("directory:"), "invalid common directory keeps usage in its recorded directory")
        let first = folder.appendingPathComponent("one/Report"), second = folder.appendingPathComponent("two/Report")
        try FileManager.default.createDirectory(at: first, withIntermediateDirectories: true)
        try FileManager.default.createDirectory(at: second, withIntermediateDirectories: true)
        expect(resolver.resolve(first.path).name == resolver.resolve(second.path).name && resolver.resolve(first.path).id != resolver.resolve(second.path).id, "same folder names keep distinct full-path identities")
        expect(resolver.resolve("") == .unknown && resolver.resolve("relative/path") == .unknown, "missing or relative directories stay unidentified")
        expect(resolver.resolve(folder.appendingPathComponent("deleted-folder").path).path.hasSuffix("deleted-folder"), "deleted absolute directories retain their recorded project")
        func task(_ id: String, _ chat: String, _ cwd: String, _ amount: Int64, _ offset: TimeInterval) -> LedgerTask {
            var usage = TokenUsage(); usage.input = amount - 10; usage.output = 10; usage.cached = 20; usage.reasoning = 5
            let date = Date(timeIntervalSince1970: 1000 + offset)
            return LedgerTask(id: id, sessionID: chat, title: "Prompt " + id, category: .coding, reason: "", usage: usage, date: date, models: ["fixture-model"], artifacts: [], finished: true, responses: 1, subagentResponses: 0, workingDirectory: cwd, lastActivity: date)
        }
        let tasks = [task("a", "chat-1", nested.path, 100, 0), task("b", "chat-1", worktree.path, 200, 1), task("c", "chat-2", repository.path, 300, 2), task("d", "chat-1", second.path, 400, 3), task("e", "chat-3", "", 50, 4)]
        let snapshot = LedgerAnalytics.enrich(LedgerSnapshot(tasks: tasks), resolver: resolver, titles: ["chat-1": "Renamed conversation"])
        expect(snapshot.projects.count == 3 && snapshot.conversations.count == 3, "multiple turns and chats aggregate into project and conversation rows")
        expect(snapshot.projects.reduce(TokenUsage()) { $0 + $1.usage } == snapshot.usage, "all project totals and subsets equal task totals")
        expect(snapshot.conversations.reduce(TokenUsage()) { $0 + $1.usage } == snapshot.usage, "all conversation totals and subsets equal task totals")
        let chat = snapshot.conversations.first { $0.id == "chat-1" }!
        expect(chat.usage.total == 700 && chat.tasks.count == 3 && chat.responses == 3, "conversation accounting sums all its turns")
        expect(chat.title == "Renamed conversation" && chat.spansProjects, "local title enrichment and cross-project badge")
        let project = snapshot.projects.first { $0.path == repository.path }!
        let scoped = project.conversations.first { $0.id == "chat-1" }!
        expect(scoped.usage.total == 300 && scoped.spansProjects && project.usage.total == 600, "project conversation excludes usage belonging to other projects")
        expect(snapshot.projects.first { $0.id == ProjectIdentity.unknown.id }?.usage.total == 50, "unknown project retains tokens")
        expect(snapshot.conversations.first { $0.id == "chat-2" }?.title == "Prompt c", "missing metadata falls back to a user request")
        expect(chat.lastActivity == tasks[3].lastActivity && project.lastActivity == tasks[2].lastActivity, "last active uses latest response time")
        expect(snapshot.projects.map { $0.usage.total } == [600, 400, 50], "projects rank by descending consumption")
        LedgerText.language = "en"
        let csv = LedgerCSV.renderProjects(snapshot.projects, translate: L)
        expect(csv.hasPrefix("\u{feff}Projects,Project path,Conversations") && csv.contains("\"600\""), "project CSV has English labels and matching totals")
        let scopedCSV = LedgerCSV.renderConversations(project.conversations, projectPath: project.path, translate: L)
        expect(scopedCSV.contains("This project only") && scopedCSV.contains("\"300\"") && !scopedCSV.contains("\"700\""), "project conversation CSV preserves scope")
        expect(LedgerCSV.renderConversations(snapshot.conversations, translate: L).contains("Entire conversation"), "global conversation CSV marks full scope")
        expect(L("1 个对话") == "1 conversation", "conversation singular translation")
        let metadata = folder.appendingPathComponent("titles.sqlite")
        var db: OpaquePointer?
        sqlite3_open(metadata.path, &db)
        sqlite3_exec(db, "CREATE TABLE threads(id TEXT, title TEXT); INSERT INTO threads VALUES('chat-1', 'Renamed conversation');", nil, nil, nil)
        sqlite3_close(db)
        let before = try Data(contentsOf: metadata)
        expect(ConversationMetadata.readTitles(metadata)["chat-1"] == "Renamed conversation", "read-only SQLite title discovery")
        let after = try Data(contentsOf: metadata)
        expect(after == before, "metadata lookup leaves the database byte-for-byte unchanged")
        let incompatible = folder.appendingPathComponent("unsupported.sqlite")
        sqlite3_open(incompatible.path, &db); sqlite3_exec(db, "CREATE TABLE threads(id TEXT);", nil, nil, nil); sqlite3_close(db)
        expect(ConversationMetadata.readTitles(incompatible).isEmpty, "incompatible metadata schema degrades to log titles")
        expect(ConversationMetadata.readTitles(folder.appendingPathComponent("absent.sqlite")).isEmpty, "metadata reader does not create a missing database")
        expect(!FileManager.default.fileExists(atPath: folder.appendingPathComponent("absent.sqlite").path), "missing metadata file stays absent")

        let parsedFile = folder.appendingPathComponent("cwd.jsonl")
        let parser = LogParser()
        let data = line("session_meta", ["id": "cwd-chat", "cwd": first.path])
            + line("event_msg", ["type": "task_started", "turn_id": "cwd-a"])
            + line("turn_context", ["turn_id": "cwd-a", "cwd": first.path, "model": "fixture"])
            + line("token_usage_record", ["thread_id": "cwd-chat", "turn_id": "cwd-a", "response_id": "cwd-ra", "usage": usage(100, 10)])
            + line("event_msg", ["type": "task_started", "turn_id": "cwd-b"])
            + line("turn_context", ["turn_id": "cwd-b", "cwd": second.path, "model": "fixture"])
            + line("token_usage_record", ["thread_id": "cwd-chat", "turn_id": "cwd-b", "response_id": "cwd-rb", "usage": usage(200, 20)])
        try data.write(to: parsedFile, atomically: true, encoding: .utf8)
        let parsed = try parser.parse(url: parsedFile)
        expect(parsed.turns["cwd-a"]?.workingDirectory == first.path && parsed.turns["cwd-b"]?.workingDirectory == second.path, "turn context records directory changes in the same conversation")
        let enriched = LedgerAnalytics.enrich(LedgerScanner().snapshot(logs: [parsed, parsed], start: .distantPast, end: .distantFuture), resolver: resolver, titles: [:])
        expect(enriched.projects.count == 2 && enriched.usage.total == 330 && enriched.conversations.count == 1, "duplicate/archived copy does not inflate project or conversation totals")
        let day = parser.date("2026-10-04T00:00:00Z")!
        let crossDay = line("session_meta", ["id": "day-chat", "cwd": first.path]) + line("event_msg", ["type": "task_started", "turn_id": "day-turn"])
            + line("token_usage_record", ["thread_id": "day-chat", "turn_id": "day-turn", "response_id": "yesterday", "usage": usage(30, 3)], "2026-10-03T23:59:00Z")
            + line("token_usage_record", ["thread_id": "day-chat", "turn_id": "day-turn", "response_id": "today", "usage": usage(40, 4)], "2026-10-04T00:01:00Z")
        try crossDay.write(to: parsedFile, atomically: true, encoding: .utf8)
        let split = LedgerAnalytics.enrich(LedgerScanner().snapshot(logs: [try parser.parse(url: parsedFile)], start: day, end: day.addingTimeInterval(86400)), resolver: resolver, titles: [:])
        expect(split.projects.first?.usage.total == 44 && split.conversations.first?.usage.total == 44, "project and conversation share per-response date boundaries")
        expect(split.conversations.first?.modelUsage.reduce(TokenUsage()) { $0 + $1.usage } == split.usage, "conversation model distribution retains response-level accounting")
        expect(enriched.projects.allSatisfy { $0.conversations.flatMap(\.modelUsage).reduce(TokenUsage()) { $0 + $1.usage } == $0.usage }, "scoped conversation models equal project totals")
        let parent = line("session_meta", ["id": "parent-chat", "cwd": first.path])
            + line("event_msg", ["type": "task_started", "turn_id": "parent-turn"])
            + line("token_usage_record", ["thread_id": "parent-chat", "turn_id": "parent-turn", "response_id": "parent-r", "usage": usage(100, 10)])
        let child = line("session_meta", ["id": "child-chat", "cwd": second.path, "source": ["subagent": ["other": "worker"]]])
            + line("event_msg", ["type": "task_started", "turn_id": "child-turn", "root_turn_id": "parent-turn"])
            + line("token_usage_record", ["thread_id": "child-chat", "turn_id": "child-turn", "root_turn_id": "parent-turn", "response_id": "child-r", "usage": usage(50, 5)])
        try parent.write(to: parsedFile, atomically: true, encoding: .utf8)
        let parentLog = try parser.parse(url: parsedFile)
        try child.write(to: parsedFile, atomically: true, encoding: .utf8)
        let childLog = try parser.parse(url: parsedFile)
        let combined = LedgerAnalytics.enrich(LedgerScanner().snapshot(logs: [parentLog, childLog, childLog], start: .distantPast, end: .distantFuture), resolver: resolver, titles: [:])
        expect(combined.projects.count == 1 && combined.projects.first?.path == first.path && combined.usage.total == 165, "deduplicated subagent usage inherits its parent project")
        expect(combined.conversations.first?.id == "parent-chat" && combined.conversations.first?.modelUsage.reduce(TokenUsage()) { $0 + $1.usage } == combined.usage, "subagent model distribution follows parent conversation")
        let demo = LedgerDemo.snapshot()
        expect(demo.projects.reduce(TokenUsage()) { $0 + $1.usage } == demo.usage && demo.conversations.reduce(TokenUsage()) { $0 + $1.usage } == demo.usage, "public synthetic demo preserves all aggregation totals")
        LedgerText.language = "zh"
    }
}

extension CoreTests {
    static func activityChecks(folder: URL) throws {
        let parser = LogParser(), scanner = LedgerScanner(timezone: TimeZone(secondsFromGMT: 0)!)
        let now = parser.date("2026-10-04T12:00:00Z")!
        let file = folder.appendingPathComponent("activity.jsonl")
        var text = line("session_meta", ["id": "activity-parent"])
            + line("event_msg", ["type": "task_started", "turn_id": "activity-turn"])
        func call(_ id: String, _ input: Int, _ timestamp: String) -> String {
            line("token_usage_record", ["thread_id": "activity-parent", "turn_id": "activity-turn", "response_id": id, "usage": usage(input, input / 10, cached: input / 2)], timestamp)
        }
        text += call("before", 900, "2026-09-04T23:59:59Z")
        text += call("first", 10, "2026-09-05T00:00:00Z")
        text += call("before-midnight", 100, "2026-09-30T23:59:59Z")
        text += call("after-midnight", 200, "2026-10-01T00:00:00Z")
        text += call("today", 30, "2026-10-04T11:00:00Z")
        text += call("future", 900, "2026-10-05T00:00:00Z")
        try text.write(to: file, atomically: true, encoding: .utf8)
        let parent = try parser.parse(url: file)
        let childText = line("session_meta", ["id": "activity-child", "source": ["subagent": ["other": "worker"]]])
            + line("event_msg", ["type": "task_started", "turn_id": "child", "root_turn_id": "activity-turn"])
            + line("token_usage_record", ["thread_id": "activity-child", "turn_id": "child", "root_turn_id": "activity-turn", "response_id": "child-call", "usage": usage(50, 5)], "2026-10-01T01:00:00Z")
        try childText.write(to: file, atomically: true, encoding: .utf8)
        let child = try parser.parse(url: file)
        let logs = [parent, parent, child, child], days = scanner.dailyUsage(logs: logs, now: now)
        expect(days.count == 30 && days.first!.date == parser.date("2026-09-05T00:00:00Z")!, "activity covers exactly 30 local calendar days including today")
        expect(days.first!.usage.total == 11 && days.last!.usage.total == 33, "activity includes the start boundary and excludes future dates")
        expect(days[25].usage.total == 110 && days[26].usage.total == 275, "cross-day turns and child responses are assigned to their actual response dates")
        expect(days.reduce(0) { $0 + $1.responses } == 5, "duplicate and archived activity copies are counted once")
        expect(days.filter { $0.usage.total == 0 }.count == 26, "missing days remain visible as zero-usage cells")
        let month = scanner.snapshot(logs: logs, start: days.first!.date, end: parser.date("2026-10-05T00:00:00Z")!)
        expect(days.reduce(TokenUsage()) { $0 + $1.usage } == month.usage, "daily token totals and cached/output subsets equal the monthly ledger")
        expect(DailyUsage(date: now).intensity(peak: 100) == 0 && days[26].intensity(peak: 275) == 4 && days.first!.intensity(peak: 275) == 1, "zero, low and peak activity have distinct bounded color levels")
        expect(scanner.dailyUsage(logs: [], now: now).allSatisfy { $0.usage.total == 0 && $0.responses == 0 }, "empty sources still have 30 dated cells")
        var la = Calendar(identifier: .gregorian); la.timeZone = TimeZone(identifier: "America/Los_Angeles")!
        let dstNow = parser.date("2026-03-09T18:00:00Z")!
        try (line("session_meta", ["id": "activity-parent"]) + call("dst-before", 10, "2026-03-08T07:30:00Z") + call("dst-after", 20, "2026-03-08T10:30:00Z")).write(to: file, atomically: true, encoding: .utf8)
        let dst = scanner.dailyUsage(logs: [try parser.parse(url: file)], now: dstNow, calendar: la)
        expect(dst[27].usage.total == 11 && dst[28].usage.total == 22 && dst[29].date.timeIntervalSince(dst[28].date) == 23 * 3600, "activity respects local midnight and the 23-hour daylight-saving day")
        expect(LedgerDemo.activity().reduce(TokenUsage()) { $0 + $1.usage } == LedgerDemo.snapshot(scope: .month).usage, "demo heatmap and monthly overview agree")
    }
}
