using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using CodexLedger;
using Forms=System.Windows.Forms;
namespace CodexLedger.Windows;
public sealed class MainWindow : Window {
    public readonly LedgerState State;private readonly DockPanel root=new();private bool overview;private TextBox? searchBox;
    private Brush FG=>new SolidColorBrush((Color)ColorConverter.ConvertFromString(State.Dark?"#E8EEF5":"#17212B"));
    private Brush BG=>new SolidColorBrush((Color)ColorConverter.ConvertFromString(State.Dark?"#151B22":"#FFFFFF"));
    private Brush CardBG=>new SolidColorBrush((Color)ColorConverter.ConvertFromString(State.Dark?"#232C35":"#F2F5F8"));
    public MainWindow(LedgerState state){State=state;Content=root;Title="Codex Ledger";Width=1080;Height=720;MinWidth=880;MinHeight=580;State.Updated+=Render;Closing+=(_,e)=>{e.Cancel=true;Hide();};Render();}
    private TextBlock Text(string text,double size=13,bool bold=false)=>new(){Text=text,FontSize=size,Foreground=FG,FontWeight=bold?FontWeights.SemiBold:FontWeights.Normal,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,3,0,3)};
    private Button Button(string label,Action action,bool enabled=true,bool translate=true){var b=new Button{Content=translate?State.T(label):label,Padding=new Thickness(10,6,10,6),Margin=new Thickness(3),IsEnabled=enabled};b.Click+=(_,_)=>action();return b;}
    private StackPanel Stack()=>new(){Margin=new Thickness(12)};
    private Border Card(UIElement content)=>new(){Child=content,Background=CardBG,Padding=new Thickness(12),CornerRadius=new CornerRadius(12),Margin=new Thickness(0,0,0,10)};
    public void ShowOverview(){overview=true;MinWidth=300;MinHeight=400;Width=320;Height=Math.Min(620,SystemParameters.WorkArea.Height-20);ShowInTaskbar=false;ResizeMode=ResizeMode.NoResize;Left=SystemParameters.WorkArea.Right-Width-12;Top=SystemParameters.WorkArea.Bottom-Height-12;Render();Show();Activate();}
    public void ShowDashboard(){overview=false;MinWidth=880;MinHeight=580;Width=Math.Min(1080,SystemParameters.WorkArea.Width-32);Height=Math.Min(720,SystemParameters.WorkArea.Height-32);ShowInTaskbar=true;ResizeMode=ResizeMode.CanResize;Left=(SystemParameters.WorkArea.Width-Width)/2;Top=(SystemParameters.WorkArea.Height-Height)/2;Render();Show();Activate();}
    public void Render(){
        if(!Dispatcher.CheckAccess()){Dispatcher.Invoke(Render);return;}Background=BG;root.Background=BG;Foreground=FG;root.Children.Clear();Title="Codex Ledger · "+(overview?State.T("用量总览"):State.Title);
        var body=Stack();
        if(!overview){var nav=Stack();nav.Width=160;nav.Background=CardBG;foreach(var (page,label) in new[]{("goals","目标账本"),("projects","项目"),("conversations","对话"),("tasks","全部任务"),("models","模型用量"),("settings","设置")})nav.Children.Add(Button(label,()=>State.Navigate(page)));nav.Children.Add(Text("Codex Ledger\n1.2.0-beta.1",10));DockPanel.SetDock(nav,Dock.Left);root.Children.Add(nav);}
        var header=new DockPanel();header.Children.Add(Text(overview?State.T("用量总览"):State.Title,overview?18:24,true));
        var actions=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};
        if(State.Page!="settings"||overview){var scopes=new ComboBox{Width=overview?106:130,Margin=new Thickness(3),ItemsSource=new[]{State.T("今天"),State.T("昨天"),State.T("近 7 天"),State.T("近 30 天"),State.T("历史累计")},SelectedIndex=(int)State.Scope};scopes.SelectionChanged+=(_,_)=>{if(scopes.SelectedIndex>=0)State.SetScope((DateScope)scopes.SelectedIndex);};actions.Children.Add(scopes);actions.Children.Add(ShareMenu());}
        actions.Children.Add(Button("刷新",async()=>await State.Refresh(),!State.Busy));DockPanel.SetDock(actions,Dock.Right);header.Children.Insert(0,actions);if(overview){body.Children.Add(Text(State.T("用量总览"),18,true));actions.HorizontalAlignment=HorizontalAlignment.Left;body.Children.Add(actions);}else body.Children.Add(header);
        if(State.Busy||!State.Ready)body.Children.Add(Text(State.T("正在整理日志，请稍候"),12));
        if(State.Error.Length>0)body.Children.Add(Text(State.T(State.Error),12));
        if(State.Current.Warnings.Count>0){body.Children.Add(Text(State.T("部分日志不可读，账本内可查看详情"),12));if(!overview)foreach(var warning in State.Current.Warnings)body.Children.Add(Text(State.T(warning),10));}
        if(!overview&&State.Page=="settings"){Settings(body);root.Children.Add(new ScrollViewer{Content=body,VerticalScrollBarVisibility=ScrollBarVisibility.Auto});return;}
        if(!overview&&(State.GoalID!=null||State.ProjectID!=null||State.ChatID!=null)){var back=new StackPanel{Orientation=Orientation.Horizontal};back.Children.Add(Button("返回",State.Back));back.Children.Add(Text(State.T(State.GoalID!=null?"仅当前目标":State.ProjectID!=null?"仅当前项目":"整个对话"),11));if(State.ChatID!=null){if(State.Lifetime.Turns.Where(t=>t.SessionID==State.ChatID).Select(t=>t.Project.ID).Distinct().Count()>1)back.Children.Add(Text(State.T("涉及多个项目"),11));back.Children.Add(Button("打开聊天",()=>OpenChat(State.ChatID)));}body.Children.Add(back);}
        var context=overview?State.Current.Turns:State.Context();Metrics(body,context);
        if(overview){body.Children.Add(Card(ShareRendering.Activity(State.Scanner.Daily(State.Month.Turns,DateTimeOffset.Now),State.T,State.Dark,FG)));body.Children.Add(Button("查看目标账本",()=>{State.Navigate("goals");ShowDashboard();}));body.Children.Add(Text(State.T("API 成本估算，非实际账单"),10));}
        else {
            if(State.GoalID!=null){var goal=State.Book.Goals.FirstOrDefault(g=>g.ID==State.GoalID);if(goal!=null){var lifetime=State.Lifetime.Turns.Where(t=>State.Book.Owner(t)==goal.ID).Aggregate(new CostEstimate(),(a,t)=>a+t.Cost);body.Children.Add(Text(State.T("累计")+": "+State.T(lifetime.Money)+" USD",18,true));if(goal.CompletionCost!=null)body.Children.Add(Text(State.T("完成时")+": "+State.T(goal.CompletionCost.Money)+" USD · "+goal.CompletedAt?.ToLocalTime().ToString("d"),13));body.Children.Add(GoalActions(goal));}}
            var filters=new StackPanel{Orientation=Orientation.Horizontal};searchBox=new TextBox{Text=State.Search,Width=300,Margin=new Thickness(3),Padding=new Thickness(7)};searchBox.ToolTip=State.T("搜索项目或路径");searchBox.TextChanged+=(_,_)=>{State.Search=searchBox.Text;UpdateRows(body);};filters.Children.Add(searchBox);filters.Children.Add(Button("清除筛选",State.Clear));if(State.Page=="goals")filters.Children.Add(Button("新建目标",()=>CreateGoal(null),State.BookReadable));body.Children.Add(filters);
            if(State.ChatID!=null){var distribution=new StackPanel();foreach(var group in context.GroupBy(t=>t.Category))distribution.Children.Add(Text(State.T(CategoryTitle(group.Key))+" · "+ShareRendering.Compact(group.Sum(t=>t.Usage.Total))+" tokens",11));foreach(var group in context.SelectMany(t=>t.Samples).GroupBy(s=>s.Model))distribution.Children.Add(Text(group.Key+" · "+ShareRendering.Compact(group.Sum(s=>s.Usage.Total))+" tokens · "+State.T(group.Aggregate(new CostEstimate(),(a,s)=>a+s.Cost).Money)+" USD",11));body.Children.Add(new Expander{Header=State.T("用途与模型分布"),Content=distribution,Foreground=FG});}
            body.Children.Add(new StackPanel{Tag="rows"});UpdateRows(body);
        }
        root.Children.Add(new ScrollViewer{Content=body,VerticalScrollBarVisibility=overview?ScrollBarVisibility.Hidden:ScrollBarVisibility.Auto});
    }
    private void Metrics(StackPanel body,IReadOnlyList<LedgerTurn> turns){var stack=new StackPanel();var cost=turns.Aggregate(new CostEstimate(),(a,t)=>a+t.Cost);var usage=turns.Aggregate(new TokenUsage(),(a,t)=>a+t.Usage);stack.Children.Add(Text(State.T("预估 API 花费")+" · USD",11));stack.Children.Add(Text(State.Known?State.T(cost.Money):State.Ready?"—":"…",overview?32:36,true));stack.Children.Add(Text(State.Known?$"{ShareRendering.Compact(usage.Total)} tokens · {turns.Count} {State.T("任务轮次")} · {turns.SelectMany(t=>t.Models).Distinct().Count()} {State.T("模型")}":"…",12));stack.Children.Add(Text(State.Range+" · "+TimeZoneInfo.Local.Id,10));body.Children.Add(Card(stack));}
    private void UpdateRows(StackPanel body){var host=body.Children.OfType<StackPanel>().FirstOrDefault(x=>Equals(x.Tag,"rows"));if(host==null)return;host.Children.Clear();var rows=State.Filter(State.Context());bool found=false;
        if(State.Page=="goals"&&State.GoalID==null&&State.ChatID==null){
            foreach(var goal in State.Book.Goals.OrderBy(g=>g.CompletedAt!=null).ThenByDescending(g=>State.Lifetime.Turns.Where(t=>State.Book.Owner(t)==g.ID).Sum(t=>t.Cost.TotalUSD))){if(State.Search.Length>0&&!goal.Name.Contains(State.Search,StringComparison.OrdinalIgnoreCase))continue;var turns=State.Current.Turns.Where(t=>State.Book.Owner(t)==goal.ID).ToArray();var group=Row(goal.Name,State.T(goal.CompletedAt==null?"进行中":"已完成"),turns,()=>{State.GoalID=goal.ID;State.Scope=DateScope.All;State.SetScope(DateScope.All);State.Clear();});group.ContextMenu=new();group.ContextMenu.Items.Add(Item("重命名目标",()=>Rename(goal)));group.ContextMenu.Items.Add(Item("删除目标",()=>Delete(goal)));host.Children.Add(Card(group));found=true;}
            var unassigned=State.Current.Turns.Where(t=>State.Book.Owner(t)==null).ToArray();host.Children.Add(Button("查看未归属任务",()=>{State.Page="tasks";State.UnassignedOnly=true;State.Search="";State.Notify();}));
        }else if(State.Page=="projects"&&State.ProjectID==null&&State.ChatID==null){foreach(var group in rows.GroupBy(t=>t.Project.ID).OrderByDescending(g=>g.Sum(t=>t.Usage.Total))){var project=group.First().Project;var row=Row(State.T(project.Name),project.Path,group.ToArray(),()=>{State.ProjectID=project.ID;State.Clear();});row.ContextMenu=Assignments("project:"+project.ID);host.Children.Add(Card(row));found=true;}}
        else if(State.ChatID==null&&(State.Page=="conversations"||State.ProjectID!=null||State.GoalID!=null)){foreach(var group in rows.GroupBy(t=>t.SessionID).OrderByDescending(g=>g.Sum(t=>t.Usage.Total))){var id=group.Key;var row=Row(State.ChatTitle(id),string.Join(" · ",group.Select(t=>t.Project.Name).Distinct()),group.ToArray(),()=>{State.ChatID=id;State.Clear();});row.ContextMenu=Assignments("conversation:"+id);host.Children.Add(Card(row));found=true;}}
        else if(State.Page=="models"){foreach(var group in rows.SelectMany(t=>t.Samples).GroupBy(s=>s.Model).OrderByDescending(g=>g.Sum(s=>s.Usage.Total))){var cost=group.Aggregate(new CostEstimate(),(a,s)=>a+s.Cost);host.Children.Add(Card(Text(group.Key+" · "+ShareRendering.Compact(group.Sum(s=>s.Usage.Total))+" tokens · "+State.T(cost.Money)+" USD",16,true)));found=true;}}
        else {foreach(var turn in rows){var row=Row(turn.Title,State.T(CategoryTitle(turn.Category))+" · "+turn.Date.ToLocalTime().ToString("g")+" · "+State.T(turn.Finished?"已结束":"未记录结束"),[turn],()=>TurnDetails(turn));row.ContextMenu=Assignments("turn:"+turn.ID);host.Children.Add(Card(row));found=true;}}
        if(!found)host.Children.Add(Text(State.T("这个范围内没有匹配的任务"),13));
    }
    private StackPanel Row(string title,string subtitle,IReadOnlyList<LedgerTurn> turns,Action open){var stack=new StackPanel();stack.Children.Add(Button(title,open,translate:false));stack.Children.Add(Text(subtitle,10));var usage=turns.Aggregate(new TokenUsage(),(a,t)=>a+t.Usage);var cost=turns.Aggregate(new CostEstimate(),(a,t)=>a+t.Cost);stack.Children.Add(Text(ShareRendering.Compact(usage.Total)+" tokens · "+State.T(cost.Money)+" USD · "+turns.Count+" "+State.T("任务轮次")+" · "+turns.Select(t=>t.SessionID).Distinct().Count()+" "+State.T("对话"),12));stack.Children.Add(Text(State.T("最近活动")+": "+(turns.Count>0?turns.Max(t=>t.LastActivity).ToLocalTime().ToString("g"):"—"),10));return stack;}
    private MenuItem Item(string label,Action action,bool enabled=true){var item=new MenuItem{Header=State.T(label),IsEnabled=enabled};item.Click+=(_,_)=>action();return item;}
    private ContextMenu Assignments(string target){var menu=new ContextMenu();foreach(var goal in State.Book.Goals){var id=goal.ID;menu.Items.Add(Item(State.T("归入目标")+": "+goal.Name,()=>{State.Book.Assign(target,id);State.SaveBook();},State.BookReadable));}menu.Items.Add(Item("新建目标并归入…",()=>CreateGoal(target),State.BookReadable));menu.Items.Add(Item("不归入目标",()=>{State.Book.Assign(target,null);State.SaveBook();},State.BookReadable));menu.Items.Add(Item("沿用上级归属",()=>{State.Book.Bindings.Remove(target);State.SaveBook();},State.BookReadable));return menu;}
    private void CreateGoal(string? target){var name=Prompt(State.T("新建目标"),"");if(string.IsNullOrWhiteSpace(name))return;var goal=new LedgerGoal(Guid.NewGuid().ToString(),name.Trim(),DateTimeOffset.Now);State.Book.Goals.Add(goal);if(target!=null)State.Book.Assign(target,goal.ID);State.SaveBook();}
    private void Rename(LedgerGoal goal){var name=Prompt(State.T("重命名目标"),goal.Name);if(string.IsNullOrWhiteSpace(name))return;int i=State.Book.Goals.FindIndex(g=>g.ID==goal.ID);State.Book.Goals[i]=goal with{Name=name.Trim()};State.SaveBook();}
    private void Delete(LedgerGoal goal){if(MessageBox.Show(State.T("删除目标只移除归属规则，不删除日志。"),State.T("删除目标"),MessageBoxButton.OKCancel)==MessageBoxResult.OK){State.Book.Remove(goal.ID);State.SaveBook();}}
    private string? Prompt(string title,string value){var window=new Window{Owner=this,Title=title,Width=400,Height=170,WindowStartupLocation=WindowStartupLocation.CenterOwner,ResizeMode=ResizeMode.NoResize,Background=BG};var stack=Stack();var input=new TextBox{Text=value,MaxLength=120,Padding=new Thickness(6)};stack.Children.Add(input);stack.Children.Add(Button("保存",()=>{window.DialogResult=true;}));window.Content=stack;return window.ShowDialog()==true?input.Text:null;}
    private StackPanel GoalActions(LedgerGoal goal){var p=new StackPanel{Orientation=Orientation.Horizontal};p.Children.Add(Button(goal.CompletedAt==null?"标记完成":"重新打开",()=>{if(goal.CompletedAt==null)State.Book.Complete(goal.ID,State.Lifetime.Turns,DateTimeOffset.Now);else State.Book.Reopen(goal.ID);State.SaveBook();},State.Ready&&!State.Busy&&State.BookReadable&&State.Lifetime.Warnings.Count==0));p.Children.Add(Button("重命名目标",()=>Rename(goal),State.BookReadable));return p;}
    private void TurnDetails(LedgerTurn turn){var window=new Window{Owner=this,Title=turn.Title,Width=560,Height=500,Background=BG,WindowStartupLocation=WindowStartupLocation.CenterOwner};var stack=Stack();stack.Children.Add(Text(turn.Title,20,true));stack.Children.Add(Text(turn.Project.Name+"\n"+turn.WorkingDirectory,12));stack.Children.Add(Text($"{turn.Usage.Total:N0} tokens · {State.T(turn.Cost.Money)} USD\n{State.T("输入")}: {turn.Usage.Input:N0} · {State.T("其中缓存")}: {turn.Usage.Cached:N0}\n{State.T("输出")}: {turn.Usage.Output:N0} · {State.T("其中推理")}: {turn.Usage.Reasoning:N0}",13));foreach(var g in turn.Samples.GroupBy(s=>s.Model))stack.Children.Add(Text(g.Key+" · "+g.Sum(s=>s.Usage.Total)+" tokens · "+State.T(g.Aggregate(new CostEstimate(),(a,s)=>a+s.Cost).Money)+" USD",12));var category=new ComboBox{ItemsSource=Categories.Select(State.T).ToArray(),SelectedIndex=Array.IndexOf(Categories,CategoryTitle(turn.Category)),Margin=new Thickness(4)};category.SelectionChanged+=(_,_)=>{if(category.SelectedIndex>=0){State.Prefs.Categories[turn.ID]=CategoryKeys[category.SelectedIndex];State.SavePreferences();}};stack.Children.Add(category);stack.Children.Add(Button("打开聊天",()=>OpenChat(turn.SessionID)));foreach(var file in turn.Artifacts)stack.Children.Add(Text(file,10));window.Content=new ScrollViewer{Content=stack};window.ShowDialog();_ = State.Refresh();}
    public static string[] CategoryKeys=["question","research","slides","document","spreadsheet","coding","image","mixed","background","unknown"];
    public static string[] Categories=["问答与学习","研究与分析","PPT 制作","Word 与写作","表格与数据","编程与调试","图片与设计","混合任务","后台检查","未分类"];
    public static string CategoryTitle(string key){int index=Array.IndexOf(CategoryKeys,key);return index>=0?Categories[index]:"未分类";}
    private void OpenChat(string id){if(!Guid.TryParse(id,out _)){MessageBox.Show(State.T("原始聊天无法打开，请在 Codex 中查找该对话。"));return;}try{Process.Start(new ProcessStartInfo("codex://threads/"+id){UseShellExecute=true});}catch(Exception){MessageBox.Show(State.T("原始聊天无法打开，请在 Codex 中查找该对话。"));}}
    private Button ShareMenu(){var button=Button("分享",()=>{} ,State.CanShare);var menu=new ContextMenu();menu.Items.Add(Item("生成分享卡片",()=>new ShareWindow(State,State.Share(overview),null){Owner=this}.ShowDialog()));menu.Items.Add(Item("保存当前界面",()=>{var image=ShareRendering.Capture(root);new ShareWindow(State,null,image){Owner=this}.ShowDialog();}));menu.Items.Add(new Separator());menu.Items.Add(Item("导出 CSV",Export));button.Click+=(_,_)=>{menu.PlacementTarget=button;menu.IsOpen=true;};return button;}
    public string ExportContents(){
        var rows=overview?State.Current.Turns:State.Filter(State.Context());var headers=new List<string>();var data=new List<IEnumerable<string>>();
        if(!overview&&State.Page=="goals"&&State.ChatID==null){headers.AddRange(new[]{"目标","统计范围","任务轮次","总tokens"});headers.AddRange(CSV.CostHeaders);headers.Add("累计总tokens");headers.AddRange(CSV.CostHeaders.Select(x=>"累计"+x));headers.Add("完成时总tokens");headers.AddRange(CSV.CostHeaders.Select(x=>"完成时"+x));foreach(var goal in State.Book.Goals.Where(g=>State.GoalID==null||g.ID==State.GoalID).Where(g=>State.Search.Length==0||g.Name.Contains(State.Search,StringComparison.OrdinalIgnoreCase))){var selected=State.Current.Turns.Where(t=>State.Book.Owner(t)==goal.ID).ToArray();var all=State.Lifetime.Turns.Where(t=>State.Book.Owner(t)==goal.ID).ToArray();var values=new List<string>{goal.Name,State.Range,selected.Length.ToString(),selected.Sum(t=>t.Usage.Total).ToString()};values.AddRange(CSV.Cost(selected.Aggregate(new CostEstimate(),(a,t)=>a+t.Cost)));values.Add(all.Sum(t=>t.Usage.Total).ToString());values.AddRange(CSV.Cost(all.Aggregate(new CostEstimate(),(a,t)=>a+t.Cost)));values.Add(goal.CompletionUsage?.Total.ToString()??"");values.AddRange(goal.CompletionCost==null?new[]{"","","","",""}:CSV.Cost(goal.CompletionCost));data.Add(values);}}
        else if(!overview&&State.Page=="models"){
            headers.AddRange(new[]{"模型","调用次数","输入tokens","缓存输入tokens","输出tokens","推理输出tokens","总tokens"});headers.AddRange(CSV.CostHeaders);
            foreach(var group in rows.SelectMany(t=>t.Samples).GroupBy(s=>s.Model)) {var u=group.Aggregate(new TokenUsage(),(a,s)=>a+s.Usage);data.Add(new[]{group.Key,group.Count().ToString(),u.Input.ToString(),u.Cached.ToString(),u.Output.ToString(),u.Reasoning.ToString(),u.Total.ToString()}.Concat(CSV.Cost(group.Aggregate(new CostEstimate(),(a,s)=>a+s.Cost))));}
        }
        else if(!overview&&State.Page=="projects"&&State.ProjectID==null&&State.ChatID==null){
            headers.AddRange(new[]{"项目","项目路径","对话数","任务轮次","总tokens","最近活动"});headers.AddRange(CSV.CostHeaders);
            foreach(var group in rows.GroupBy(t=>t.Project.ID)){var p=group.First().Project;data.Add(new[]{State.T(p.Name),p.Path,group.Select(t=>t.SessionID).Distinct().Count().ToString(),group.Count().ToString(),group.Sum(t=>t.Usage.Total).ToString(),group.Max(t=>t.LastActivity).ToString("O")}.Concat(CSV.Cost(group.Aggregate(new CostEstimate(),(a,t)=>a+t.Cost))));}
        }
        else if(!overview&&(State.ChatID!=null||State.ProjectID!=null||State.GoalID!=null||State.Page=="conversations")){
            headers.AddRange(new[]{"对话","聊天ID","项目路径","统计范围","任务轮次","调用次数","总tokens","最近活动"});headers.AddRange(CSV.CostHeaders);
            foreach(var group in rows.GroupBy(t=>t.SessionID)){data.Add(new[]{State.ChatTitle(group.Key),group.Key,string.Join("; ",group.Select(t=>t.Project.Path).Distinct()),State.Range+" · "+State.T(State.GoalID!=null?"仅当前目标":State.ProjectID!=null?"仅当前项目":"整个对话"),group.Count().ToString(),group.Sum(t=>t.Responses).ToString(),group.Sum(t=>t.Usage.Total).ToString(),group.Max(t=>t.LastActivity).ToString("O")}.Concat(CSV.Cost(group.Aggregate(new CostEstimate(),(a,t)=>a+t.Cost))));}
        }
        else {headers.AddRange(new[]{"任务","聊天ID","项目","项目路径","统计范围","输入tokens","缓存输入tokens","输出tokens","推理输出tokens","总tokens","模型","目标"});headers.AddRange(CSV.CostHeaders);foreach(var t in rows)data.Add(new[]{t.Title,t.SessionID,State.T(t.Project.Name),t.Project.Path,State.Range,t.Usage.Input.ToString(),t.Usage.Cached.ToString(),t.Usage.Output.ToString(),t.Usage.Reasoning.ToString(),t.Usage.Total.ToString(),string.Join("; ",t.Models),State.Book.Goals.FirstOrDefault(g=>g.ID==State.Book.Owner(t))?.Name??State.T("未归入目标")}.Concat(CSV.Cost(t.Cost)));}
        return CSV.Render(new[]{headers.Select(State.T)}.Concat(data));
    }
    private void Export(){var dialog=new Microsoft.Win32.SaveFileDialog{Filter="CSV (*.csv)|*.csv",FileName="Codex-Ledger.csv"};if(dialog.ShowDialog(this)==true)try{File.WriteAllText(dialog.FileName,ExportContents(),new UTF8Encoding(false));}catch(Exception){MessageBox.Show(State.T("保存失败，请重试"));}}
    private void Settings(StackPanel p){p.Children.Add(Text(State.T("数据来源"),18,true));p.Children.Add(Text(State.Prefs.Source));p.Children.Add(Button("选择 Codex 数据目录…",async()=>{using var dialog=new Forms.FolderBrowserDialog{SelectedPath=State.Prefs.Source};if(dialog.ShowDialog()==Forms.DialogResult.OK){State.Prefs.Source=dialog.SelectedPath;State.GoalID=null;State.ProjectID=null;State.ChatID=null;State.Ready=false;State.SavePreferences();State.LoadBook();await State.Refresh();}},!State.Busy));
        p.Children.Add(Text(State.T("语言"),16,true));var language=new ComboBox{ItemsSource=new[]{"English","简体中文"},SelectedIndex=State.Prefs.Language=="zh"?1:0,Width=220,HorizontalAlignment=HorizontalAlignment.Left};language.SelectionChanged+=(_,_)=>{State.Prefs.Language=language.SelectedIndex==1?"zh":"en";State.SavePreferences();State.Notify();};p.Children.Add(language);
        p.Children.Add(Text(State.T("外观"),16,true));var appearance=new ComboBox{ItemsSource=new[]{State.T("跟随系统"),State.T("浅色"),State.T("深色")},SelectedIndex=State.Prefs.Appearance=="dark"?2:State.Prefs.Appearance=="light"?1:0,Width=220,HorizontalAlignment=HorizontalAlignment.Left};appearance.SelectionChanged+=(_,_)=>{State.Prefs.Appearance=new[]{"system","light","dark"}[appearance.SelectedIndex];State.SavePreferences();State.Notify();};p.Children.Add(appearance);
        var login=new CheckBox{Content=State.T("登录时启动"),IsChecked=State.Prefs.LaunchAtLogin,Foreground=FG,Margin=new Thickness(0,14,0,14)};login.Click+=(_,_)=>{try{using var key=Microsoft.Win32.Registry.CurrentUser.CreateSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run");if(login.IsChecked==true)key.SetValue("CodexLedger","\""+Environment.ProcessPath+"\"");else key.DeleteValue("CodexLedger",false);State.Prefs.LaunchAtLogin=login.IsChecked==true;State.SavePreferences();}catch(Exception){MessageBox.Show(State.T("设置保存失败，请重试。"));}};p.Children.Add(login);
        p.Children.Add(Text(State.T("API 成本估算，非实际账单")+" · "+Pricing.Date,12));p.Children.Add(Text(State.T("只读本机记录，不上传聊天内容。"),12));p.Children.Add(Button("下载与安装帮助",()=>Process.Start(new ProcessStartInfo(ShareSnapshot.DownloadURL){UseShellExecute=true})));
    }
}
